void Orient_Correction(int BLKS_NUM, hardblock **blks_arr);
void Create_Init_Bstree(int BLKS_NUM, hardblock **blks_arr, sort_node *sorted_list);
sort_node *Sort_Blks(int BLKS_NUM, int W, int H, hardblock **blks_arr);
void Init_Floorplan(hardblock *parent, int *contour, int W);
bool Sorted_Floorplan(int BLKS_NUM, int W, int H, hardblock **blks_arr, sort_node *sorted_list);
void Flip_Sorted_Floorplan(hardblock **blks_arr, sort_node *sorted_list, int W, int H);
void Globally_Compact(hardblock **blks_arr, sort_node *sorted_list, int *contour, int W, int H);
void Row_Based_Adjust(hardblock **blks_arr, sort_node *sorted_list, int W, int H);
int get_hpwl(net *nets_ptr);
sort_node *Row_Change(hardblock **blks_arr, sort_node *sorted_list, int W, int H, net **nets_arr, int NETS_NUM, tml **tmls_arr);